name: Run
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Install OpenCV
      with:
        opencv-version: '4.1.0'
    - name: Build
      run: sh build.bash
