name: Run
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Install GCC
      uses: egor-tensin/setup-gcc@v1
    - name: Install OpenCV
      uses: rayandrews/with-opencv-action@v1
      with:
        cached: false
        opencv-version: '4.1.0'
    - name: Build
      run: sh build.bash
    - uses: actions/cache@v2
      with:
        path: | 
          opencv-install/
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: out
        path: build/out.jpg
